---

version: "3.3"

networks:
  internal-network:
    internal: true
  external-network:

volumes:
  postgres_data:
  static_volume:

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=juntagrico
      - POSTGRES_USER=juntagrico
      - POSTGRES_PASSWORD=juntagrico
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      internal-network:

  proxy:
    image: traefik:v2.4
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      external-network:
      internal-network:
    depends_on:
      - app
      - web

  web:
    image: nginx:1.19-alpine
    environment:
      NGINX_CONFIG: |
        server {
          listen 8001;
          location / {
            alias /home/app/web/static/;
          }
        }
    command:
      - /bin/sh
      - -c
      - |
        echo "$$NGINX_CONFIG" > /etc/nginx/conf.d/default.conf
        sed -e "s/error_log.*/error_log\ \/dev\/null\ crit;/g" -e "s/access_log.*/access_log\ \/dev\/null;/g" -i /etc/nginx/nginx.conf
        nginx -g "daemon off;"
    volumes:
      - static_volume:/home/app/web/static
    labels:
      - traefik.enable=true
      - traefik.http.services.web.loadbalancer.server.port=8001
      - traefik.http.routers.web.rule=(Host(`localhost`) && PathPrefix(`/static`))
      - traefik.http.middlewares.web-compress.compress=true
      - traefik.http.middlewares.web-stripprefix.stripprefix.prefixes=/static
      - traefik.http.routers.web.middlewares=web-compress@docker,web-stripprefix@docker
    networks:
      internal-network:
    expose:
      - 8001
    depends_on:
      - app

  app:
    image: rotebeete/juntagrico
    environment:
      JUNTAGRICO_DATABASE_BACKEND: django.db.backends.postgresql
      JUNTAGRICO_DATABASE_NAME: juntagrico
      JUNTAGRICO_DATABASE_USER: juntagrico
      JUNTAGRICO_DATABASE_PASS: juntagrico
      JUNTAGRICO_DATABASE_HOST: db
    labels:
      - traefik.enable=true
      - traefik.http.services.app.loadbalancer.server.port=8000
      - traefik.http.routers.app.rule=Host(`localhost`)
    volumes:
      - static_volume:/home/app/web/static
    networks:
      internal-network:
    depends_on:
      - db
