---

name: Build Docker image
on:
  push:
    branches: main
    tags: "v*.*.*"
    paths-ignore:
      - '**/README.md'
      - '**/LICENSE.md'
      - '**/docker-compose.yml'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Extract tag from github.ref
        id: docker-tag
        uses: yuya-takeyama/docker-tag-from-github-ref-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: rotebeete/juntagrico:${{ steps.docker-tag.outputs.tag }}
